import random
from funcoes_do_jogo import *

print('Paciência Acordeão')
print('------------------')
print(' ')
print('Seja bem vindo(a) ao jogo Paciência Acordeão! O objetivo do jogo é colocar todas as cartas na mesma pilha!')
print(' ')
print('Regras:')
print(' ')
print('Existem apenas dois movimentos possíveis:')
print('1) Empilhar uma carta sobre a carta imediatamente anterior;')
print('2) Empilhar uma carta sobre a terceira carta anterior.')
print(' ')
print('Para que um movimento possa ser realizado basta que uma das duas condições abaixo seja atendida:')
print('1) As duas cartas possuem o mesmo valor')
print('                 OU')
print('2) As duas cartas possuem o mesmo naipe.')
print(' ')
print('Desde que alguma das condições acima seja satisfeita, qualquer carta pode ser movimentada.')
print(' ')
print(input('Aperte ENTER para começar o jogo: '))
print(' ')
print('O estado do baralho atual é: ')
